# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_server_win(object):
    def setupUi(self, server_win):
        server_win.setObjectName("server_win")
        server_win.resize(444, 446)
        server_win.setStyleSheet("background-color:#FFFFFF")
        self.ip_edit = QtWidgets.QLineEdit(server_win)
        self.ip_edit.setGeometry(QtCore.QRect(100, 30, 221, 61))
        self.ip_edit.setStyleSheet("border:0px;   \n"
"margin:10px;     \n"
"margin-left:50px;    \n"
"margin-right:50px;        \n"
"border-bottom: 2px solid #B3B3B3;     \n"
"border-bottom-color :#39C45D;\n"
"font-family:黑体; \n"
"font-size:20px;     \n"
"font-weight:bold;    ")
        self.ip_edit.setObjectName("ip_edit")
        self.port_edit = QtWidgets.QLineEdit(server_win)
        self.port_edit.setGeometry(QtCore.QRect(100, 90, 221, 61))
        self.port_edit.setStyleSheet("border:0px;   \n"
"margin:10px;     \n"
"margin-left:50px;    \n"
"margin-right:50px;        \n"
"border-bottom: 2px solid #B3B3B3;     \n"
"border-bottom-color :#39C45D;\n"
"font-family:黑体; \n"
"font-size:20px;     \n"
"font-weight:bold;    ")
        self.port_edit.setObjectName("port_edit")
        self.run_btn = QtWidgets.QPushButton(server_win)
        self.run_btn.setGeometry(QtCore.QRect(24, 190, 81, 41))
        self.run_btn.setStyleSheet("background-color:#39C45D;\n"
"border-radius:10px")
        self.run_btn.setObjectName("run_btn")
        self.groupBox = QtWidgets.QGroupBox(server_win)
        self.groupBox.setGeometry(QtCore.QRect(120, 180, 201, 141))
        self.groupBox.setStyleSheet("boder-color:#39C45D")
        self.groupBox.setObjectName("groupBox")
        self.status = QtWidgets.QTextEdit(self.groupBox)
        self.status.setGeometry(QtCore.QRect(10, 20, 181, 111))
        self.status.setStyleSheet("border-color:#39C45D")
        self.status.setObjectName("status")

        self.retranslateUi(server_win)
        self.run_btn.clicked.connect(server_win.startServer)
        QtCore.QMetaObject.connectSlotsByName(server_win)

    def retranslateUi(self, server_win):
        _translate = QtCore.QCoreApplication.translate
        server_win.setWindowTitle(_translate("server_win", "Form"))
        self.ip_edit.setPlaceholderText(_translate("server_win", "IP"))
        self.port_edit.setPlaceholderText(_translate("server_win", "PORT"))
        self.run_btn.setText(_translate("server_win", "启动"))
        self.groupBox.setTitle(_translate("server_win", "连接信息"))
